{% set setup_data = load_setup_py_data() %}
package:
  name: bam-filter
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/genomewalker/bam-filter.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python==3.9
    - setuptools
    - pip
    - Cython>=0.29.24
    - cxx-compiler
  run:
    - python==3.9
    - Cython>=0.29.24
    - cxx-compiler
    
test:
  commands:
    - filterBAM -h

about:
  home: https://github.com/genomewalker/bam-filter
  summary: "A simple tool to filter references from a BAM  file using different filter types"
  license: {{ setup_data['license'] }}
  license_file: LICENSE
